### ISSUE TITLE
How to get event when user drags row of el-table?

### ISSUE THREAD

**Issue by react-hunter** [WakuwakuP/element-ui-el-table-draggable#5]
I could implement `sortable` on el-table by using this library.
But, I can't get any event when user drags row of el-table.
Can you explain about the events of this library?

**Comment by WakuwakuP** [comment]
Thanks for using.
It is not reactive because it uses `this.$children`.
I can add function.

```vue
<el-table-draggable @drop="func()">
```

**Comment by therRed** [comment]
did you added this event? I got the same problem

**Comment by therRed** [comment]
I see, your file's code --event name is "dorp"  not "drop" ,hhhhh  You may have misspelled the word.
thanks for your share

**Comment by WakuwakuP** [comment]
Thank you.
Corrected the misspell the word.
You can use "drop" by updating to 1.2.1
