### ISSUE TITLE
Missing dist folder and build files on npm server

### ISSUE THREAD

**Issue by ka2jun8** [WakuwakuP/element-ui-el-table-draggable#8]
I found the following error when I installed lement-ui-el-table-draggable and build my project.

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'element-ui-el-table-draggable' in ...
```

I think it is missing a 'dist' folder and build files.

```
✗ ls node_modules/element-ui-el-table-draggable
LICENSE.txt  README.md    package.json src
```

I tried following processes and succeed to build my project using element-ui-el-table-draggable.

- cd node_modules/element-ui-el-table-draggable
- npm i
- mkdir build
- vim build/rollup.config.js // <- copy from github
- vim src/entry.js // <- copy from github
- npm run build

Could you publish the latest build files?

**Comment by WakuwakuP** [comment]
thanks. I will fix it soon.

**Comment by WakuwakuP** [comment]
fixed
